- name: Install Golang
  ansible.builtin.command:
    cmd: ./install-go.sh
    chdir: $HOME/bin
    creates: $HOME/go/bin

- name: Install GolangCi-lint
  ansible.builtin.command:
    cmd: ./install-golangci.sh
    chdir: $HOME/bin
    creates: $HOME/.gopath/bin/golangci-lint
